# Generated by Django 5.2.8 on 2025-11-11 14:23

import isbn_field.fields
import isbn_field.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('quantity', models.PositiveIntegerField()),
                ('authors', models.CharField()),
                ('book_type', models.CharField()),
                ('publisher', models.CharField()),
            ],
        ),
    ]
