# Generated by Django 5.2.8 on 2025-11-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aservo', '0002_alter_book_options_book_created_book_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, null=True),
        ),
    ]
