# Generated by Django 5.2.8 on 2025-11-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aservo', '0005_book_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
