# Generated by Django 5.2.8 on 2025-11-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aservo', '0006_remove_book_year_book_publisher_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_date',
            new_name='publish_date',
        ),
    ]
