# Generated by Django 5.2.7 on 2025-10-30 11:25

import acervo_de_livros.models
import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Indica o tipo de livro ex: Quadrinho, Crônica brasileira, ect', verbose_name='Nome do tipo de livro')),
            ],
        ),
        migrations.CreateModel(
            name='LivroRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text='Digite um ISBN válido (ex: 978-85-12345-67-8 ou 85-12345-67-X)', max_length=20, unique=True, validators=[acervo_de_livros.models.valida_codigo_isbn], verbose_name='Código ISBN do livro')),
                ('titulo', models.CharField(verbose_name='Título do livro')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de cópias')),
                ('autores', models.TextField(help_text='Autor ou autores do livro', verbose_name='Autor(es)')),
                ('edicao', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número da edição')),
                ('ano_publicação', models.CharField(validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')], verbose_name='Ano da públicação do livro')),
                ('editora', models.CharField(verbose_name='Editora do livro')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo_de_livros.tipolivro')),
            ],
        ),
    ]
