# Generated by Django 5.2.7 on 2025-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo_de_livros', '0002_rename_ano_publicação_livroregistro_ano_publicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livroregistro',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=0, help_text='Este campo idica a quantidade real de livros disponiveis para serem pegos pelos alunos', verbose_name='Quantidade de cópias disponiveis para os alunos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livroregistro',
            name='autores',
            field=models.CharField(help_text='Autor ou autores do livro', verbose_name='Autor(es)'),
        ),
    ]
