# Generated by Django 5.2.7 on 2025-10-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo_de_livros', '0003_livroregistro_quantidade_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livroregistro',
            options={'verbose_name': 'Livro Registrado', 'verbose_name_plural': 'Livros Registrados'},
        ),
        migrations.AlterModelOptions(
            name='tipolivro',
            options={'verbose_name': 'Tipo de Livro', 'verbose_name_plural': 'Tipos de Livro'},
        ),
    ]
