# Generated by Django 5.2.7 on 2025-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo_de_livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livroregistro',
            old_name='ano_publicação',
            new_name='ano_publicacao',
        ),
        migrations.AlterField(
            model_name='livroregistro',
            name='editora',
            field=models.CharField(blank=True, null=True, verbose_name='Editora do livro'),
        ),
    ]
