# Generated by Django 5.2.7 on 2025-10-30 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acervo_de_livros', '0004_alter_livroregistro_options_alter_tipolivro_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(verbose_name='Nome do aluno')),
                ('metricula', models.CharField(verbose_name='Matrícula do aluno')),
            ],
            options={
                'verbose_name': 'Aluno Registrado',
                'verbose_name_plural': 'Alunos Registrados',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(verbose_name='Data de retirada do livro')),
                ('data_renovacao', models.DateField(verbose_name='Data programada para a renovação do emprestimo do livro')),
                ('data_renovacao_2', models.DateField(blank=True, help_text='Em caso de a primeira data de renovação não ter sido efetivada.', null=True, verbose_name='Segunda data para a renovação do emprestimo do livro')),
                ('data_devolucao', models.DateField(blank=True, help_text='Data em que o aluno devolveu o livro requisitado.', null=True, verbose_name='Data da devolução')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_de_emprestimo.alunoregistro', verbose_name='Aluno que solicitou o livro')),
                ('funcionario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário responsável')),
                ('livro', models.ForeignKey(help_text="Esse valor faz referência a um livro registrado no módulo de 'Acervo de livros'.", on_delete=django.db.models.deletion.CASCADE, to='acervo_de_livros.livroregistro', verbose_name='Livro solicitado pelo aluno')),
            ],
        ),
    ]
